### ISSUE TITLE
Blender stops responding to any Artnet input after light type is changed

### ISSUE THREAD

**Issue by tornel** [BryanCrotaz/blender-artnet#1]
Steps to reproduce:

- Open New default file 
- Change light type to Spot
- Enable ArtNet Light Control and set Fixture Type, Universe And Base DMX Adress
- Confirm everything is working ok with the Artnet sender (QLC+)
- Change light type to anything but spotlight (Point, Area or Sun)
- Change any channel value in QLC+ (<- This is important!)
- **Blender stops responding to any Artnet input, even if you change the light type back to Spot.**

Note: To get it working again it is not sufficient to reopen the file or start a new file, you must close Blender and reopen it again. 

Edit:
Tested in Windows with Blender 2.82 and QLC+ 4.12.2

**Comment by BryanCrotaz** [comment]
It only works with spotlights - they're the only light that looks like a real world fixture. I'll modify the docs

**Comment by BryanCrotaz** [comment]
Feel free to submit a PR that enables support of other light types - look at the `src/blender_sync.py` file

**Comment by BryanCrotaz** [comment]
Please try this again with the Blender terminal open and see if any errors are raised

**Comment by tornel** [comment]
I undesrtand that it will work only whith spotlights, it is logic. 

However the problem is that the plugin itself stops working.

PS. I am no coder

**Comment by tornel** [comment]
Will try with the terminal and report back

**Comment by BryanCrotaz** [comment]
It's in the Window menu - Toggle System Console

**Comment by tornel** [comment]
This is the relevent output:

```
Traceback (most recent call last):
  File "C:\Users\Luis\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-artnet-master\src\blender_sync.py", line 29, in _update_blender
    self._update_blender_from_universe(universe_index)
  File "C:\Users\Luis\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-artnet-master\src\blender_sync.py", line 50, in _update_blender_from_universe
    obj.data.spot_size = self._get_zoom(universe, base_address, fixture_type) or 0
AttributeError: 'AreaLight' object has no attribute 'spot_size'

```

**Comment by BryanCrotaz** [comment]
Fix released (v1.3), and now supports Area lights too

**Comment by tornel** [comment]
Wow! That was fast! Thank you so much

**Comment by BryanCrotaz** [comment]
If you find it useful, please help me spend more time on it - https://www.patreon.com/bcrotaz
