### ISSUE TITLE
No AutoKeying when pilot Light with Artnet

### ISSUE THREAD

**Issue by Atreyus86** [BryanCrotaz/blender-artnet#10]
Probally beacause the add_on modify the "delta trasform" rather than "transform" the auto keying isn't possible.You think that there is a possibility to fix this issue?It is very very essential for render animation with pan tilt movement synced with LTC.

**Comment by BryanCrotaz** [comment]
Describe your workflow?

**Comment by Atreyus86** [comment]
As you have seen from the screenshots before we are moving the fixture with artnet generated from ma2 wing.
We have a LTC track (Song on Left ch - LTC on Right ch) that syncs the movevement with the song, we need to record the keyframe automatically when we play the show.

**Comment by Atreyus86** [comment]
LTC->MA2(lightdesk)->Artnet->Blender->AutoKeying

**Comment by BryanCrotaz** [comment]
This plugin is designed for real-time use. Are you rendering with cycles in non-real-time?

Not sure why you need key frames as artnet will control the lighting as LTC moves on.

**Comment by Atreyus86** [comment]
The reason is simple, i create my show with some movement of light beam, i would like that those movement will be register by auto keying in the timeline of Blender for rendering and create a video that i can use for spot or for integration in othet project that require seguently rendering animation.
And off course, we want to use cycles for better accuracy and quality of rendering animation and eevee only for "real time" visualization

**Comment by BryanCrotaz** [comment]
If rendering in non real time it feels like Blender should be generating artnet time code from the currently rendering frame.

**Comment by BryanCrotaz** [comment]
I wonder if the delta transforms are needed now that you can change which axis is affected by the transform. If you want to rotate the initial location of the fixture you can do that on the parent. That way you'd still get auto keyframes. Would you be happy with that?

**Comment by BryanCrotaz** [comment]
if I get this working, please submit some documentation as a PR describing how you've set up Blender to render your animation from timecode in non-real-time.

**Comment by BryanCrotaz** [comment]
v1.5 should work.

**Comment by Atreyus86** [comment]
> v1.5 should work.

Thanks, tomorrow I will try the new version

**Comment by BryanCrotaz** [comment]
v1.6.1 has much improved keyframing
