### ISSUE TITLE
Can't get connected

### ISSUE THREAD

**Issue by MMagneson** [BryanCrotaz/blender-artnet#2]
Great initiative!

I got this going with an MA onPC yesterday, but today it seems like it won't connect for some reason. I can imagine this being due to multiple ethernet interfaces on the computer. Would it be possible to list the interface currently being used by Blender somwhere?

I also had some issues seemingly related to scaling values yesterday, but I'll make a pull request once I figure that bit out.

**Comment by BryanCrotaz** [comment]
It's binding to all ethernet interfaces:
```python
UDP_IP = "0.0.0.0"
UDP_PORT = 6454
```
So I'm not sure why it wouldn't connect. You'll need to tell MA where to send the Artnet universe - you should be able to use any IP address bound to one of your adaptors.

**Comment by MMagneson** [comment]
Thank you, I got it working again now by setting the UDP IP to 127.0.0.1 to lock it to the MA output IP. It might be an issue in the system as MA sees 5 interfaces including the loopback (I have 3 physical).

There also is some confusion in the universe numbering, as MA/artnetominator uni 1 is uni 2 in Blender. I think there is a difference in QLC and MA in handling Art-Net (1-based vs 0-based).

**Comment by BryanCrotaz** [comment]
The Artnet spec gives numbering starting at 1 I think - that's why I did it that way

**Comment by BryanCrotaz** [comment]
> I got it working again now by setting the UDP IP to 127.0.0.1

You set that in the blender code, or in MA? You should only have to set it in MA. The blender code binds to 0.0.0.0 which means it will accept data on any IP interface on this computer including 127.0.0.1.

**Comment by MMagneson** [comment]
I set it in the Blender code. Before doing that I also got a warning about using multiple addresses/sockets from Windows in the console.

**Comment by BryanCrotaz** [comment]
That's odd - I've used it successfully on Windows 10

**Comment by BryanCrotaz** [comment]
Try using https://pypi.org/project/netifaces/ to list all the interfaces, and instead of one socket binding to `0.0.0.0`, create a socket for each network interface.

**Comment by BryanCrotaz** [comment]
Happy to accept a PR if you can fix this

**Comment by BryanCrotaz** [comment]
@hesse2 did you get this working?

**Comment by BryanCrotaz** [comment]
Try the new version 1.4 too.
