### ISSUE TITLE
Blender 2.83.2

### ISSUE THREAD

**Issue by Atreyus86** [BryanCrotaz/blender-artnet#7]
installation in Blender version higher than 2.80 is not possible.
I tried first with the latest version of Blender and then with the version you suggest.
With the suggested version the addon works correctly but with the new version of Blender I think there are some bugs. How can I help you solve this problem?

**Comment by BryanCrotaz** [comment]
Bring up the system console with _Window > Toggle System Console_

Do you see any errors in there? If not try disabling then enabling the plugin to see if it only reports errors on startup.

**Comment by BryanCrotaz** [comment]
Then when you've found the error, this is a great excuse to learn python. I'd never used it before this project and I had the first version running in a couple of hours.

**Comment by Atreyus86** [comment]
> Bring up the system console with _Window > Toggle System Console_
> 
> Do you see any errors in there? If not try disabling then enabling the plugin to see if it only reports errors on startup.

the plugin isn't visible in the list of the add on in last version of blender, while in the old version after installing it appears in the list

**Comment by BryanCrotaz** [comment]
Hmm. I'm not at home at the moment, but when I'm there I'll try upgrading Blender and see what's wrong.

**Comment by BryanCrotaz** [comment]
Sorry for the delay - I'm not a lighting designer so this is a pure hobby project. I've released v1.4 which works for me in 2.83. It's not enabled by default after installation, so check that you're not just listing enabled addons.

**Comment by BryanCrotaz** [comment]
Definitely works in v1.6 - I've been using Blender 2.83.3 for testing
