### ISSUE TITLE
Refresh Add_on

### ISSUE THREAD

**Issue by Atreyus86** [BryanCrotaz/blender-artnet#9]
When i close the project and after that i re-open the same project, i have to uncheck and recheck the flag on the ArtNet addon and only after that it starts to work again

**Comment by BryanCrotaz** [comment]
I can't reproduce this with 1.4 - please test again

**Comment by BryanCrotaz** [comment]
there is a bug fix in 1.4 where the artnet socket wasn't closed properly if the plugin was unloaded.

**Comment by Atreyus86** [comment]
when i close and re-open one project with only one fixture (maybe even 2 - 4 - 6) the refresh work perfectly, but when i open other project with 32 fixture (i don't know why) the refresh don't  work.

**Comment by BryanCrotaz** [comment]
Can you pm me your blender file?

**Comment by Atreyus86** [comment]
yes off course, how can i send you in PM mode?

**Comment by BryanCrotaz** [comment]
Email is on my profile

**Comment by BryanCrotaz** [comment]
Fixed in v1.5
